---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/11/4 17:28
---

local M = {
    item_data = {},
}

function M:updateItem(data)
    for k, v in pairs(data) do
        self.item_data[tonumber(k)] = v
    end
end

function M:RemoveItem(data)
    for k, v in pairs(data) do
        self.item_data[tonumber(v)] = nil
    end
end

function M:GetNumById(id)
    return self.item_data[id] or 0
end

function M:getItemCfgById(id)
    if id then
        id = tonumber(id)
        local item_cfg = ConfigManager:getCfgByName("item")
        return item_cfg[id]
    end
end

function M:getItemsByType(item_sort)
    local items = {}
    for k,v in pairs(self.item_data) do
        local cfg = self:getItemCfgById(k)
        if cfg.sort == item_sort then
            items[#items + 1] = {id = tonumber(k), data = v, cfg = cfg}
        end
    end
    return items
end

return M