---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/12/16 17:27
---

local M = {
    package_data = {},
    goods_times = {},
    max_lv = {},
    pos_num = 0,
    open_pos_num = 0,
    package_exp = 0,
}

function M:UpdatePackageByPos(data)
    self.curr_updateData = self.curr_updateData or {} 
    for pos, package_id in pairs(data) do
        self.curr_updateData[pos] = pos
        self.package_data[pos] = package_id[1]
    end
    self:InitPosNum()
end

function M:InitPosNum()
    local num = 0
    for k, v in pairs(self.package_data) do
        if v then
            num = num + 1
        end
    end
    local a = num % 4
    if a == 0 then
        self.pos_num = num
    else
        self.pos_num = num + (4 - a)
    end
    self.open_pos_num = num
end

function M:GetNumOnpenPos()
    return self.open_pos_num
end

function M:InitTimes(data)
    for package_id, times in pairs(data) do
        self.goods_times[package_id] = times
    end
end

function M:InitMaxLv(data)
    for type=1, 3 do
        local typeStr = tostring(type+3)
        if data[typeStr] then
            self.max_lv[type] = data[typeStr]
        end
    end
end

function M:InitPackageExp(exp)
    self.package_exp = exp
end

function M:GetPackageData()
    return self.package_data
end

function M:GetGoodsTimesById(package_id)
    return self.goods_times[tostring(package_id)] or 0
end

function M:GetMaxLvByType(type)
    if not type then
        return 0
    end
    return math.max(1, self.max_lv[type] or 0)
end

function M:GetPackageExp()
    return self.package_exp
end

return M