---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2020/11/10 10:14
---

local M = {
    story_data = {},
}

function M:updateStory(data)
    local data = data or {}
    self.story_cfg = ConfigManager:getCfgByName("story")
    for k, v in pairs(self.story_cfg) do
        self.story_data[k] = v
        self.story_data[k].id = k
        self.story_data[k].state = 0
        if self:CheckOpen(k) then
            self.story_data[k].state = 1
        end
        if data[tostring(k)] then
            self.story_data[k].state = 2
        end
    end
    self:Sort(self.story_data)
end

function M:AddStory(data)
    local data = data or {}
    for k, v in pairs(self.story_data) do
        if v.state == 0 then
            if self:CheckOpen(v.id) then
                v.state = 1
            end
        end
        for m, n in pairs(data) do
            if v.id == tonumber(m) then
                v.state = n
            end
        end
    end
    self:Sort(self.story_data)
end

function M:CheckOpen(story_id)
    local is_open = true
    local cur_story_cfg = self.story_cfg[story_id]
    if cur_story_cfg.unlock_type == 1 then --关卡
        local stage =  UserDataManager:getCurStage()
        is_open = cur_story_cfg.unlock_parm <= stage
    elseif cur_story_cfg.unlock_type == 2 then --声望等级
        local star = UserDataManager.user_data:getUserStatusDataByKey("star")
        is_open = cur_story_cfg.unlock_parm <= star
    end
    return is_open
end

-- 排序
function M:Sort(list)
    --1:可阅读>0:未解锁>2:已阅读排序，同类下按id排序
    local sort1, sort2
    local sortFunc = function(a, b)
        sort1 = a.state
        sort2 = a.state
        if a.state == 2 then
            sort1 = 10000 + a.id
        elseif a.state == 1 then
            sort1 = 1000 + a.id
        elseif a.state == 0 then
            sort1 = 5000 + a.id
        end
        if b.state == 2 then
            sort2 = 10000 + b.id
        elseif b.state == 1 then
            sort2 = 1000 + b.id
        elseif b.state == 0 then
            sort2 = 5000 + b.id
        end
        return sort1 < sort2
    end
    table.sort(list, sortFunc)
end

function M:GetStoryState()
    return self.story_data
end

return M