-- Dotween动画
Tweening = CS.DG.Tweening
DOTweenModuleUI = Tweening.DOTweenModuleUI
require("Framework.Init")
Unpacking = require("Util.Unpacking")
Unpacking:init()
Bit = require("bit")
NetUrl = require("Net.NetUrl")
NetWork = require("Net.NetWork")
PathUtil = require("Util.PathUtil")
GameUtil = require("Util.GameUtil")
require("DataCenter.Init")
AnimUtil = require("Util.AnimUtil")
RewardUtil = require("Util.RewardUtil")
SDKUtil = require("Util.SDKUtil")
SDKUtil:init()
PayUtil = require("Util.PayUtil")
LoopScrollUtil = require("Util.LoopScrollUtil")
MaskSlider = require("Util.MaskSlider")
PingPangMotion = require("Util.PingPangMotion")
SceneUtil = require("Util.SceneUtil")
CarouselUtil = require("Util.CarouselUtil")
QuickOpenFuncUtil = require("Util.QuickOpenFuncUtil")
RedPointUtil = require("Util.RedPointUtil")
LoopScrollViewUtil = require("Util.LoopScrollViewUtil")
BtnOpenUtil = require("Util.BtnOpenUtil")
ResourceUtil = require("Util.ResourceUtil")
--ChatUtil = require("Util.ChatUtil")
audio = require("Util.AudioUtil")
CommonUIUtil = require("Util.CommonUIUtil")
StatisticsUtil = require("Util.StatisticsUtil")