---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2021/3/3 10:24
---

local M = {}

--获取背景图目录
function M:GetBgPath(img_name)
    local img_path = "Texture/bg/" .. tostring(img_name)
    return img_path
end

--获取大服饰图标目录
function M:GetBigClothesIconPath(img_name)
    local img_path = "Texture/big_clothes_icon/" .. tostring(img_name)
    return img_path
end

--获取大背景图标目录
function M:GetBigBgIconPath(img_name)
    local img_path = "Texture/big_bg_icon/" .. tostring(img_name)
    return img_path
end

--获取男友立绘目录
function M:GetBoyPath(img_name)
    local img_path = "Texture/Boy/" .. tostring(img_name)
    return img_path
end

--获取男友约会详情目录
function M:GetBoyStageInfoPath(img_name)
    local img_path = "Texture/boy_ui/" .. tostring(img_name)
    return img_path
end

--获取服装目录
function M:GetClothesPath(img_name)
    local img_path = "Texture/Clothes/" .. tostring(img_name)
    return img_path
end

--获取立绘目录
function M:GetFigurePath(img_name)
    local img_path = "Texture/Figure/" .. tostring(img_name)
    return img_path
end

--获取多语言目录
function M:GetLanguagePath(img_name)
    local cur_lan = Language:getCurLanguage()
    local img_path = "Texture/bg_language_" .. cur_lan.. "/" .. tostring(img_name)
    return img_path
end

--获取活动目录
function M:GetActivityPath(img_name)
    local img_path = "Texture/Activity/" .. tostring(img_name)
    return img_path
end

--获取PK立绘目录
function M:GetPkPath(img_name)
    local img_path = "Texture/Pk/" .. tostring(img_name)
    return img_path
end

return M