---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2021/3/10 10:41
---

local M = {}

M.m_network_tips = true

function M:init()
    self.UnpackingGameObject =  CS.UnityEngine.GameObject.Find("UnpackingGameObject")
    self.m_Hotupdate = self.UnpackingGameObject:GetComponent("HotUpdate")
    self.m_Uncompress = self.UnpackingGameObject:GetComponent("Uncompress")
    self.fileName = nil
    self.md5 = nil
    self.fileSize = nil
end

--下载
function M:downloadRes()
    local url_lists = UserDataManager.server_data:getResourceUrl()
    if #url_lists > 0 and self.fileName then
        local url = url_lists[1] .. self.fileName
        local function httpStatus(msg, data)
            self:responseCode(msg, data)
        end
        local function slider(cur, total)
            local data = {cur = cur, total = total}
            EventDispatcher:dipatchEvent(GlobalConfig.EVENT_KEYS.UNPACKING_EVENT, { event = "slider_update", data = data })
        end
        self.m_Hotupdate:DownLoadFile(self.fileName, url, self.md5, httpStatus, slider, self.fileSize)
        EventDispatcher:dipatchEvent(GlobalConfig.EVENT_KEYS.UNPACKING_EVENT, { event = "start_update" })
    end
end

--解压
function M:decompressFile()
    local function decompressStatus(msg, data)
        self:responseCode(msg, data)
    end
    local function slider(cur, total)
        local data = {cur = cur, total = total}
        EventDispatcher:dipatchEvent(GlobalConfig.EVENT_KEYS.UNPACKING_EVENT, { event = "slider_decompress", data = data })
    end
    self.m_Uncompress:Decompress(decompressStatus, slider)
    EventDispatcher:dipatchEvent(GlobalConfig.EVENT_KEYS.UNPACKING_EVENT, { event = "start_decompress" })
end

--stop
function M:CanCELAndDeleteZip()
    self.m_Hotupdate:CancelDownLoad()
    --self.m_Uncompress:CancelDownLoad()
end

function M:responseCode(msg, data)
    if msg == "isDone" then -- 资源下载完成
        Logger.log(data, "isDone  ==== ")
        if data == 0 then -- 下载完成 去解压
            self:decompressFile()
        elseif data == 1 then -- MD5校验失败 从新下载
            self:downloadRes()
        end
    elseif msg == "code" then
        Logger.log(data, "Update http code ==== ")
    elseif msg == "UncompressCode" then
        if data == 0 then -- 解压完成
            --UserDataManager.local_data:setLocalDataByKey("later_md5", self.md5)
            U3DUtil:PlayerPrefs_SetString("later_md5", self.md5)
            StatisticsUtil:sendBundlesPointLog("DownloadBundles")
            EventDispatcher:dipatchEvent(GlobalConfig.EVENT_KEYS.UNPACKING_EVENT, { event = "end_decompress" })
        end
    end
end

-- 检测网络环境，是否是WiFi
function M:networkStatusReachable(callback)
    if callback then
        local netType = GameUtil:getNetworkReachability()
        if netType == "wifi" then
            callback()
        elseif netType == "4G" then
            local params =
            {
                on_ok_call = function(msg)
                    U3DUtil:PlayerPrefs_SetString("down_4g", "down")
                    callback()
                end,
                on_cancel_call = function (msg)
                    U3DUtil:PlayerPrefs_SetString("down_4g", "")
                    callback()
                end,
                no_close_btn = false,
                tow_close_btn = true,
                text = Language:getTextByKey("update_str_0021")
            }
            static_rootControl:openView("Pops.CommonPop", params)
        else
            local params =
            {
                on_ok_call = function(msg)
                    GameMain.reStart()
                end,
                on_cancel_call = function (msg)
                end,
                no_close_btn = true,
                text = Language:getTextByKey("update_str_0005")
            }
            static_rootControl:openView("Pops.CommonPop", params)
        end
    else
        local params =
        {
            on_ok_call = function(msg)
                GameMain.reStart()
            end,
            on_cancel_call = function (msg)
            end,
            no_close_btn = true,
            text = Language:getTextByKey("update_str_0008")
        }
        static_rootControl:openView("Pops.CommonPop", params)
    end
end

return M